before:
  hooks:
    # clean up/install modules
    - go mod tidy
    - "go run tools/windows_metadata/release.go v{{- .Version }}"
builds:
  - main: 
    hooks:
      pre:
      - "rm -f resource.syso"
      - "go generate"
    ignore:
    - goos: windows
      goarch: arm64
    ldflags:
      - '{{ if eq .Os "windows" }}-H=windowsgui{{ end }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge:'
      - '^docs:'
      - '^test:'
      - '^[Bb]ump'
      - '^[Cc]lean'
